/***************************************************
*
*	includes.h
*
*	Generated by
*	AVR Wizard v1.0.4163.35676
*	Copyright 2011, Chirag Sangani
*	Electronics Club, IIT Kanpur
*	http://students.iitk.ac.in/eclub
*
*	Project Name:   project1
*	Date Created:   28/11/2021 11:00:37 p. m.
*	Author:         
*   Company:        
*	Comments:       
*   
*	Chip:           ATmega16
*	Frequency:      8.00000 MHz
*
***************************************************/

#ifndef INCLUDES
#define INCLUDES

#define F_CPU 8000000

#include <avr/io.h>
#include <avr/interrupt.h>

#endif
